### ISSUE TITLE
Upload to TestFlight without triggering 2FA 

### ISSUE THREAD

**Issue by Max-Might** [microsoft/app-store-vsts-extension#153]
Hello,

According to [this comment](https://github.com/fastlane/fastlane/issues/14617#issuecomment-484284843) (and [this PR](https://github.com/fastlane/fastlane/pull/14456) - merged) FastLane supports uploading to TestFlight using the app-specific password only and without triggering 2FA.

This happens if the following conditions are met:
- `apple_id` should be provided
- `skip_waiting_for_build_processing` should be set

I see there is a checkbox for the second one in the UI but I do not see the first one.
Is it possible to configure the release task in such a way as to not trigger 2FA when uploading the binary? I do not need to update metadata or anything else, just uploading the binary.

**Comment by Max-Might** [comment]
Hello? Is this extension still maintained?

You could at least expose a fastlane as an extension so people can to this themselves?

**Comment by aelbialyTR** [comment]
Anyone knows the answer to this question? I'm trying to figure out as well how to upload to TestFlight without triggering 2FA

**Comment by anton-erofeev** [comment]
Hi @Max-Might 
Yes, it's possible to configure the release task to not trigger 2FA. 
Please take a look at an example of such a task:
```
- task: AppStoreRelease@1
  inputs:
    authType: 'UserAndPass'
    username: '$(fastLane.auth.userName)'
    password: '$(fastLane.auth.password)'
    isTwoFactorAuth: true
    appSpecificPassword: '$(fastLane.auth.appPassword)'
    fastlaneSession: '$(fastLane.auth.session)'
    appIdentifier: '$(fastLane.auth.bundleID)'
    appType: 'iOS'
    ipaPath: '**/*.ipa'
    releaseTrack: 'TestFlight' 
    shouldSkipWaitingForProcessing: true
    fastlaneArguments: '-p 1234567890'
```

The following conditions are required:

- apple id should be provided (-p "your apple id" in fastlaneArguments input )
- shouldSkipWaitingForProcessing: true
- isTwoFactorAuth: true

Please let me know if it solves your issue

**Comment by Max-Might** [comment]
I think this works for a short while and when the session expires 2FA gets triggered again.

**Comment by anton-erofeev** [comment]
Hi, @Max-Might 

We are working on a solution, but there is currently a workaround: please try passing any non-empty string to the fastlaneSession input.
For example: 
```
- task: AppStoreRelease@1
  inputs:
    authType: 'UserAndPass'
    username: '$(fastLane.auth.userName)'
    password: '$(fastLane.auth.password)'
    isTwoFactorAuth: true
    appSpecificPassword: '$(fastLane.auth.appPassword)'
    fastlaneSession: 'anyNotEmptyString'
    appIdentifier: '$(fastLane.auth.bundleID)'
    appType: 'iOS'
    ipaPath: '**/*.ipa'
    releaseTrack: 'TestFlight' 
    shouldSkipWaitingForProcessing: true
    fastlaneArguments: '-p 1234567890'
```
