### ISSUE TITLE
fastlane deliver: Potential server error received: 'Unexpected Error'

### ISSUE THREAD

**Issue by danimal521** [microsoft/app-store-vsts-extension#154]
Hey guys,

There were issues when apple updated their API, fastlane was updated. When will these show up in the "Apple App Store" plugin? Here is a link to the PR/Issue:

https://github.com/fastlane/fastlane/issues/16621

Thanks!

**Comment by sapunhan** [comment]
I had a similar problem, I was able to target the specific version to 2.150.0.rc1 for a quick fix

**Comment by danimal521** [comment]
> I had a similar problem, I was able to target the specific version to 2.150.0.rc1 for a quick fix

I did the same but still have issues. Can you share your YAML step? Here is mine.

    - task: AppStoreRelease@1
      inputs:
        serviceEndpoint: 'Apple'
        appIdentifier: 'com.Flashop'
        appType: 'iOS'
        ipaPath: '**/*.ipa'
        releaseTrack: Production
        skipBinaryUpload: false
        shouldSubmitForReview: true
        shouldAutoRelease: true
        fastlaneToolsVersion: SpecificVersion
        fastlaneToolsSpecificVersion: 2.150.0.rc1

**Comment by sapunhan** [comment]
I've only tried updating metadata so far but the server errors went away.

```
- task: AppStoreRelease@1
  displayName: 'Publish to the App Store Production track'
  inputs:
    serviceEndpoint: ' app store connection'
    appIdentifier: ****
    ipaPath: '**/*.ipa'
    releaseTrack: Production
    uploadMetadata: true
    metadataPath: '$(System.DefaultWorkingDirectory)/metadata'
    fastlaneToolsVersion: SpecificVersion
    fastlaneToolsSpecificVersion: 2.150.0.rc1
```
