### ISSUE TITLE
IDFA is required to submit

### ISSUE THREAD

**Issue by mobileappd** [microsoft/app-store-vsts-extension#160]
Hi there,

I'm not sure if this is something already addressed and I just missed it, but since a few months idfa is required to submit an app to the app store. If it is not specified, you get an error like:

[!] Use of Advertising Identifier (IDFA) is required to submit
Add information to the :submission_information option...
  Docs: http://docs.fastlane.tools/actions/deliver/#compliance-and-idfa-settings
  Example: submission_information: { add_id_info_uses_idfa: false }
  Example: submission_information: {
    add_id_info_uses_idfa: true,
    add_id_info_serves_ads: false,
    add_id_info_tracks_install: true,
    add_id_info_tracks_action: true,
    add_id_info_limits_tracking: true
  }
  Example CLI:
    --submission_information "{\"add_id_info_uses_idfa\": false}"

Seeing as this is a requirement to submit, is there a chance this can be added as a required field in the task? 

We're currently not sure how to add it otherwise, we're going to test it through our pipeline during our next release in a few weeks by adding additional arguments to fastlane through the field provided by the extension, but since it required, a field in the tasks seems like a more logical place imo.

**Comment by luizgrs** [comment]
fastLaneArguments seems to do not work here:

```
- task: AppStorePromote@1
            inputs:
              ...
              fastlaneArguments: '-b "{\"add_id_info_uses_idfa\": false}"'
```
fails with 

> [!] 'submission_information' value must be a Hash! Found String instead.

and using the long arg name also fails:

```
          - task: AppStorePromote@1
            inputs:
              ...
              fastlaneArguments: '--submission_information "{\"add_id_info_uses_idfa\": false}"'
```

> invalid option: --submission_information "{\"add_id_info_uses_idfa\": false}"

It seems fastlaneArguments doesn`t work quite well, I also had other issues when trying to use it to setup -z and had to fallback to environment variables. but environment variable isn`t an option for submission_information..

According to fastlane docs using the argument that way should work. I tried in my computer and it worked. The issue might be in how that extra arguments are getting appended to the command
