### ISSUE TITLE
Multiple parameters in Additional Fastlane Parameters not handled correctly in App Store Promote task 

### ISSUE THREAD

**Issue by luizgrs** [microsoft/app-store-vsts-extension#164]
fastlaneArguments does not work with multiple parameters (or arguments followed by values).

I`ve seen issues when trying to use it to setup -z and had to fallback to environment variables. but not all args options have environment variable like submission_information..

Example 1
```
- task: AppStorePromote@1
            inputs:
              ...
              fastlaneArguments: '-z 2.0.9'
```

Is incorrectly parsed and gets one space added at the beggining:

```
+--------------------------------------+------------------+
|                 deliver 2.156.1 Summary                 |
+--------------------------------------+------------------+
...
| build_number                         | 2.0.9            |
| skip_binary_upload                   | true             |
| skip_metadata                        | true             |
| skip_screenshots                     | true             |
| force                                | true             |
| app_version                          |  2.0.9           |
                                        ^^two spaces here

....
18:29:10]: Making sure the latest version on App Store Connect matches ' 2.0.9'...
                                                                        ^additional space again
....

```

Example 2:
```
- task: AppStorePromote@1
            inputs:
              ...
              fastlaneArguments: '-z "2.0.9" --submission_information "{\"add_id_info_uses_idfa\": false}"'
```
```
+--------------------------------------+------------------------------------------------------------------------+
|                                            deliver 2.156.1 Summary                                            |
+--------------------------------------+------------------------------------------------------------------------+
| username                             | ***                                                         |
| build_number                         | 2.0.9.9365                                                             |
| skip_binary_upload                   | true                                                                   |
| skip_metadata                        | true                                                                   |
| skip_screenshots                     | true                                                                   |
| force                                | true                                                                   |
| app_version                          |  "2.0.9" --submission_information "{\"add_id_info_uses_idfa\": false}" |
```
