### ISSUE TITLE
Error when I try to Release with build skipped

### ISSUE THREAD

**Issue by NPadrutt** [microsoft/app-store-vsts-extension#206]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question / bug

**Enter Task Name**:  Apple App Store Release  

## Environment

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Release all -> Promote iOS to Production
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I try to promote a iOS built to from Testflight to Produciont. This is my task:

```
steps:
- task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
  displayName: 'Publish to the App Store Production track'
  inputs:
    serviceEndpoint: 'Apply Solutions Apple Store'
    appIdentifier: com.applysolutions.moneyfox
    releaseTrack: Production
    skipBinaryUpload: true
    uploadMetadata: true
    metadataPath: '$(System.DefaultWorkingDirectory)/_iOS Release/drop/metadata'
    shouldSubmitForReview: true
    shouldAutoRelease: true
    fastlaneArguments: '--submission_information "{\"add_id_info_uses_idfa\": false}"'

```

And I get the error you see in the logs. From the issues on GitHub that I found, that would hint at a problem with the 2FA. But I use the same service connection as I do for the test flight which has 2FA disabled.
Also, when I remove the "Skip Binary Upload" option I don't get that error and it seems to upload correctly. So to me that sounds like that the basic connection and auth does work.

Also, funny enough a couple of months ago I was already at the point that builds could be submitted and that I just had the release notes missing. Since I haven't changed anything on the pipeline itself, so it seems that something on the task / fastlane changed.

[Include task name(s), screenshots and any other relevant details]

### Task logs

[ReleaseLogs_310.zip](https://github.com/microsoft/app-store-vsts-extension/files/5876286/ReleaseLogs_310.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by anatolybolshakov** [comment]
Hi @NPadrutt could you please try to run it with fastlane '--verbose' flag?

**Comment by NPadrutt** [comment]
hey @anatolybolshakov 

here are those logs:

[ReleaseLogs_312.zip](https://github.com/microsoft/app-store-vsts-extension/files/5888247/ReleaseLogs_312.zip)

**Comment by anatolybolshakov** [comment]
@NPadrutt there was a fix for issue https://github.com/microsoft/app-store-vsts-extension/issues/174 - according to [current fastlane logic](https://github.com/fastlane/fastlane/blame/f55ec210827f1f7e6f3b77f4b19f73f1154d23f6/deliver/lib/deliver/commands_generator.rb#L69) it requires either description, or metadata, or deliver file to be specified in case of skipping of binary file. We are planning to extend current help info for 'Skip Binary Upload' regarding it.
Could you please try to specify one of these inputs to resolve it?

**Comment by NPadrutt** [comment]
@anatolybolshakov  I already had release notes defined via a metadata folder. Although I extended that for the description:

![image](https://user-images.githubusercontent.com/1764367/106436924-f8e9fc00-6474-11eb-945d-e5ff9ca85f5a.png)

But so far the logs seem the same. Would I have to declare that differently?

**Comment by anatolybolshakov** [comment]
@NPadrutt do you have 'metadata' inside of fastlane directory?

**Comment by NPadrutt** [comment]
no, you should see the hiearchy on the image in my comment before or here
![image](https://user-images.githubusercontent.com/1764367/106458731-1c22a480-6491-11eb-8d32-12ab7a39bd1f.png)

and I set the metadata path to that:
![image](https://user-images.githubusercontent.com/1764367/106459275-e92ce080-6491-11eb-8e88-32b095177712.png)

**Comment by anatolybolshakov** [comment]
@NPadrutt ok I see, got it 👍 Let me take a look

**Comment by kevcrooks** [comment]
@anatolybolshakov We'd be keen to know of a solution to this as well. I think we have the same case where a build is already on TestFlight, but would like to automate the process of sending for review (which requires adding our new metadata).

Our setup seems to be the same, but when running the task with "Skip Binary Upload" and "Upload Metadata" selected, we get the message `Cannot find edit app store version...`

**Comment by anatolybolshakov** [comment]
@NPadrutt According to fastlane code it tries to find metadata folder inside of fastlane folder or current working directory- so it seems it doesn't consider custom metadata path... This seems to be a fastlane issue - could you please create ticket in [fastlane repo](https://github.com/fastlane/fastlane)?
@kevcrooks hmm, this issue looks little bit different - could you please share your logs containing this error?

**Comment by kevcrooks** [comment]
@anatolybolshakov yes I've attached the log, replacing some paths,ids and names with [...] but hopefully gives enough detail. 
[BuildLog.txt](https://github.com/microsoft/app-store-vsts-extension/files/5964212/BuildLog.txt)

We have successfully deployed a binary to TestFlight already, and the purpose of this build is to use the `Apple App Store Release` task with `skip binary upload` selected, so that it will promote our existing TestFlight build to production, add metadata (the release notes) and submit for review.

I've played with a few settings to see if some combination will work, but haven't been able to find. If you think this is a separate issue I can raise a new one though? Here is our yaml:

```
steps:
- task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
  displayName: 'Publish to the App Store Production track'
  inputs:
    serviceEndpoint: 'Apple App Store'
    appIdentifier: [...]
    releaseTrack: Production
    skipBinaryUpload: true
    uploadMetadata: true
    metadataPath: '[...]/appMetadata'
    shouldSubmitForReview: true
    shouldAutoRelease: true
    fastlaneArguments: '--submission_information "{\"export_compliance_uses_encryption\": false, \"add_id_info_uses_idfa\": false }" --verbose'
```

From the fastlane docs above, it appears I need to use `fastlane deliver submit_build`, whereas the pipeline is using `fastlane deliver` only - can you let me know how we can do a promotion from TestFlight to Production

**Comment by jawi-bq** [comment]
Hi @kevcrooks, thanks to your comment I was able to move build from TestFlight to AppStore with skipBinary by using this as fastlane arguments: 
`submit_build --build_number $(RELEASE_VERSION_CODE) --submission_information "{\"export_compliance_uses_encryption\": false, \"add_id_info_uses_idfa\": false }" --description`
where `RELEASE_VERSION_CODE` is my CFBundleVersion.

**Comment by NPadrutt** [comment]
As a work around for me worked to just add a PowerShell script before the upload step that moves the metadata folder to the root of the working directory:

```
$PathMetadata = "$(System.DefaultWorkingDirectory)/iOS_Release/drop/metadata"
$PathMetadataNew = "$(System.DefaultWorkingDirectory)"

Move-Item -Path $PathMetadata -Destination $PathMetadataNew
```

The issue for fastlane is created. We'll see if they can find something.

**Comment by NPadrutt** [comment]
While my work around solved the initial issue I had, meanwhile I have the same as @kevcrooks. Funny enough, when I create a build and directly promote it through testflight to production it works. But when I do the promoting a day or two later I get the  `Cannot update languages - could not find an editable version for 'IOS'` Error

**Comment by jawi-bq** [comment]
@NPadrutt  `could not find editable version` means your are trying to submit changes to a build which is not present in the App Store yet. You can create a new version manually form App Connect or just add another parameter to the fastlane arguments: `--app_version $(RELEASE_VERSION_NAME)` where `RELEASE_VERSION_NAME` is your CFBundleShortVersionString.

**Comment by NPadrutt** [comment]
@jawi-bq  thanks for the tipp. I'll try the --app_version parameter in the next publish.  I'm just kinda puzzled that it sometimes seems to work when you directly go through. But maybe there is something going together with the TestFlight release or that I opened something with my tests that I wasn't aware of.

**Comment by NPadrutt** [comment]
This is like whack a mole..  Now I get the error:  "Unsupported directory name(s) for screenshots/metadata " despite having deactivated that screenshots should be uploaded and not having made any changes to the meta data..

**Comment by anatolybolshakov** [comment]
@NPadrutt @let us take a look if we could make a workaround at the moment at the task level - to avoid metadata path being ignored.
@kevcrooks have you tried to use promote task?

**Comment by AndreyBespamyatnov** [comment]
After 3 days, I found a workaround, hope that will be useful and will save some time for you:

1. Create a metadata folder structure via PS script
```
New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "metadata" -ItemType "directory"

New-Item -Path "$(System.DefaultWorkingDirectory)\metadata\" -Name "en-US" -ItemType "directory"
New-Item -Path "$(System.DefaultWorkingDirectory)\metadata\" -Name "default" -ItemType "directory"

New-Item -Path "$(System.DefaultWorkingDirectory)\metadata\en-US\" -Name "release_notes.txt" -ItemType "file" -Value "We update our app regularly to provide you with the best experience and stability."
New-Item -Path "$(System.DefaultWorkingDirectory)\metadata\default\" -Name "release_notes.txt" -ItemType "file" -Value "We update our app regularly to provide you with the best experience and stability."
```
2. Create a new release
```

steps:
- task: AppStoreRelease@1
  displayName: 'Publish to the App Store Production track'
  inputs:
    serviceEndpoint: 'IT@Surgent Apple'
    releaseTrack: Production
    appIdentifier: **************************
    ipaPath: '$(System.DefaultWorkingDirectory)/**************************.ipa'
    skipBinaryUpload: true
    uploadMetadata: true
    metadataPath: '$(System.DefaultWorkingDirectory)/metadata'
    shouldSubmitForReview: true
    shouldAutoRelease: true
    fastlaneArguments: '--app_version $(buildString) --build_number $(buildIdWithOffset) --submission_information "{\"export_compliance_uses_encryption\": false, \"add_id_info_uses_idfa\": false }"  --verbose'
```
************************** - sensitive data 
$(buildString) = 1.0.1755 (CFBundleShortVersionString)
$(buildIdWithOffset) = 1755 (CFBundleVersion)
