### ISSUE TITLE
Submitting already uploaded binary for Apple Review fails because "No deliver configuration found in the current directory."

### ISSUE THREAD

**Issue by SEnglishSMP** [microsoft/app-store-vsts-extension#230]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Apple App Store Release

## Environment
- Server - Azure Pipelines
- Agent - Hosted macOS

## Issue Description

A previous stage in our release pipeline uploads the app to TestFlight.  The one in question then adds metadata and submits the already uploaded binary for review by Apple.  This used to work.  

Due to Apple's requirement for 2FA, we instead turned to using an API key.  According to [Fastlane documentation](https://docs.fastlane.tools/app-store-connect-api/), API keys are fully supported for `deliver` and this task has a way to configure that, so it should work.  The previous stage (uploading to TestFlight) still works correctly (now that we're using an API key), but submitting to Apple Review fails.  The logs show:

    [19:47:15]: No deliver configuration found in the current directory. Do you want to setup deliver?

...after which the process tanks because it's not running in interactive mode.  

The error indicates that Fastlane is not being called correctly.  This may be related to #206, however the use of API keys differs as does the error messages returned, so I'm opening a new ticket.  Note that we are providing metadata.

The YAML provided by the UI is below.  I've replaced the app identifier with "[...]".

```
steps:
- task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
  displayName: 'Submit app for Review'
  inputs:
    authType: ApiKey
    apiKeyId: '$(AppStoreConnectAPIKeyID)'
    apiKeyIssuerId: '$(AppStoreConnectAPIKeyIssuerID)'
    apitoken: '$(AppStoreConnectAPIKeyContent)'
    appIdentifier: [...]
    releaseTrack: Production
    skipBinaryUpload: true
    uploadMetadata: true
    metadataPath: '$(System.DefaultWorkingDirectory)/_iOS release/drop/AppStore/metadata'
    shouldSubmitForReview: true
    fastlaneArguments: '--submission_information "{\"add_id_info_uses_idfa\": false}"'
```

### Task logs

_NOTE:_ I've replaced potentially sensitive information with "..." in the logs.
[ReleaseLogs_305.zip](https://github.com/microsoft/app-store-vsts-extension/files/6251044/ReleaseLogs_305.zip)

### Error logs

    [19:47:15]: No deliver configuration found in the current directory. Do you want to setup deliver?
