### ISSUE TITLE
[AppStoreRelease] Install specific Fastlane version doesn't work properly

### ISSUE THREAD

**Issue by miketimofeev** [microsoft/app-store-vsts-extension#245]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AppStoreRelease  

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - Azure Pipelines, canary org https://buildcanary.visualstudio.com/PipelineCanary/_build/results?buildId=1562871&view=logs&j=cbcc884e-5cf2-50a7-8031-bc9d5c2deff7&t=8ce14790-71b8-529b-0e04-35575eeb0bb9

- Agent - Hosted or Private: 
    Hosted — azure pipelines, macOS-10.15

## Issue Description

I've tried to install a specific Fastlane version to avoid this issue https://github.com/microsoft/app-store-vsts-extension/issues/244 using the following code:
```
  - task: AppStoreRelease@1
    displayName: 'Publish to the App Store TestFlight track'
    inputs:
      serviceEndpoint: '$(apikey_service_endpoint_name)'
      appIdentifier: '$(app_identifier_name)'
      ipaPath: '$(build.artifactstagingdirectory)/**/*.ipa'
      shouldSkipWaitingForProcessing: true
      shouldSkipSubmission: true
      installFastlane: true
      isTwoFactorAuth: true
      fastlaneArguments: "-p $(apple_app_id)"
      fastlaneToolsVersion: SpecificVersion
      fastlaneToolsSpecificVersion: 2.183.0
```
Strangely, the output shows successful 2.184.0 installation and as well successful 2.183.0 installation but the following steps still use version 2.184.0, not sure what went wrong
![image](https://user-images.githubusercontent.com/48208649/119342514-dd159a80-bc9d-11eb-8e87-f506f23f59aa.png)

### Task logs
https://buildcanary.visualstudio.com/deeb2bf9-e13d-4e1b-acc1-bf9844b08d19/_apis/build/builds/1562871/logs/76

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2021-05-24T11:33:57.7558720Z [command]/usr/local/opt/ruby@2.7/bin/gem uninstall fastlane -a -I
2021-05-24T11:33:59.3867750Z Removing bin-proxy
2021-05-24T11:33:59.3869260Z Removing fastlane
2021-05-24T11:33:59.3870330Z Successfully uninstalled fastlane-2.184.0
2021-05-24T11:33:59.3992650Z [command]/usr/local/opt/ruby@2.7/bin/gem install fastlane -v 2.183.0
2021-05-24T11:34:25.5487980Z Successfully installed fastlane-2.183.0
2021-05-24T11:34:25.5489360Z Parsing documentation for fastlane-2.183.0
2021-05-24T11:34:25.5490470Z Installing ri documentation for fastlane-2.183.0
2021-05-24T11:34:25.5491210Z Done installing documentation for fastlane after 22 seconds
2021-05-24T11:34:25.5491930Z 1 gem installed
```
