### ISSUE TITLE
invalid option: --submission_information

### ISSUE THREAD

**Issue by idelfonsog2** [microsoft/app-store-vsts-extension#263]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: `invalid option: --submission_information`

**Enter Task Name**: AppStoreRelease

## Environment
- Server - Azure Pipelines or TFS on-premises? **Azure Pipelines**
 
- Agent - Hosted or Private: Hosted macOS-11

### Task Description

```
- task: AppStoreRelease@1
  inputs:
    serviceEndpoint: 'AppStoreConnectConnection'
    teamId: // for issue purpose
    appSpecificId: // for issue purpose
    releaseTrack: 'TestFlight'
    appIdentifier: // for issue purpose
    appType: 'iOS'
    distributedToExternalTesters: false
    externalTestersGroups: // for issue purpose
    fastlaneArguments: '--submission_information "{\"export_compliance_uses_encryption\": true, \"add_id_info_uses_idfa\": true }" --verbose'
```

### Task logs
```
INFO [2021-11-23 16:48:06.28]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
invalid option: --submission_information
##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
Finishing: AppStoreRelease
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

`invalid option: --submission_information`
