### ISSUE TITLE
Distribute Only fails due to FastLane requiring app_platform value which is not set

### ISSUE THREAD

**Issue by IainS1986** [microsoft/app-store-vsts-extension#381]
Using AppStoreRelease@1 task to only distribute a previously publishing build to more test groups.

```
  - task: AppStoreRelease@1
    displayName: Promote build to Internal Company group
    inputs:
      authType: 'ApiKey'
      apiKeyId: '$(ios.auth.keyid)'
      apiKeyIssuerId: '$(ios.auth.issuerid)'
      apitoken: '$(ios.auth.token)'
      appType: 'iOS'
      releaseTrack: 'TestFlight'
      distributeOnly: true
      appIdentifier: '$(ios.bundleid)'
      appBuildNumber: '$(release.buildnumber)'
      externalTestersGroups: 'Stakeholders, Internal Company'
      shouldSkipWaitingForProcessing: true
```
      
      
 This fails because FastLane enters interactive mode asking for the app type
` [09:15:07]: Please enter the app's platform (appletvos, ios, osx, xros): `

I've seen a while back there was an issue raised in fastlane when this occured but I think the resolution is just that you have to now set `app_platform`
https://github.com/fastlane/fastlane/issues/19351

Looking at the code for the task I can see that appType is only processed in **production** tracks, not **TestFlight** ones, so `distributeOnly` is failing.
