### ISSUE TITLE
Upgraded to ruby 3.3.6 on build agent: error (Gem::MissingSpecVersionError)

### ISSUE THREAD

**Issue by Brendan-Koehler-PrePass** [microsoft/app-store-vsts-extension#388]
Hello, we updated our build server to use ruby 3.3.6 and are running into this issue when using the app store release task, if we use an earlier version of ruby (Tested with 3.1.4, 3.0.0, and 2.7) it works without this issue: 

```
Starting: AppStoreRelease
==============================================================================
Task         : Apple App Store Release
Description  : Release an app to TestFlight or the Apple App Store
Version      : 1.234.0
Author       : Microsoft Corporation
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
==============================================================================
/Users/devops/myagent/_work/_tool/Ruby/3.3.6/x64/bin/gem install fastlane
Ignoring digest-crc-0.6.5 because its extensions are not built. Try: gem pristine digest-crc --version 0.6.5
Successfully installed fastlane-2.226.0
Parsing documentation for fastlane-2.226.0
Installing ri documentation for fastlane-2.226.0
Done installing documentation for fastlane after 32 seconds
1 gem installed
/Users/devops/myagent/_work/_tool/Ruby/3.3.6/x64/bin/gem update fastlane -i /Users/devops/.gem-cache
Updating installed gems
Nothing to update
Gems already up-to-date: fastlane
/Users/devops/.gem-cache/bin/fastlane pilot upload --api_key_path /Users/devops/myagent/_work/_temp/api_key***.json -i /Users/devops/myagent/_work/2/build/appstore/output/PrePass.ipa -a *** --skip_submission true --skip_waiting_for_build_processing true -p 00000000
/Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1417:in `rescue in block in activate_dependencies': Could not find 'sysrandom' (~> 1.0) among 174 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/devops/.local/share/gem/ruby/3.3.0:/Users/devops/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0:/Users/devops/.gem-cache' at: /Users/devops/.gem-cache/specifications/fastlane-sirp-1.0.0.gemspec, execute `gem env` for more information
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1414:in `block in activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1421:in `block in activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems.rb:280:in `block in activate_bin_path'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `synchronize'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `activate_bin_path'
	from /Users/devops/.gem-cache/bin/fastlane:25:in `<main>'
/Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/dependency.rb:303:in `to_specs': Could not find 'sysrandom' (~> 1.0) - did find: [sysrandom-1.0.5] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/devops/.local/share/gem/ruby/3.3.0:/Users/devops/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0:/Users/devops/.gem-cache' , execute `gem env` for more information
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1415:in `block in activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1421:in `block in activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems.rb:280:in `block in activate_bin_path'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `synchronize'
	from /Users/devops/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `activate_bin_path'
	from /Users/devops/.gem-cache/bin/fastlane:25:in `<main>'
##[error]Error: The process '/Users/devops/.gem-cache/bin/fastlane' failed with exit code 1
```

Task:
```
          - task: AppStoreRelease@1
            inputs:
              authType: 'ApiKey'
              apiKeyId: $(AppStoreConnectAPIKeyID)
              apiKeyIssuerId: $(AppStoreConnectIssuerID)
              apitoken: $(setAPIkey.base64key)
              appIdentifier: $(Identifier)
              appType: 'iOS'
              ipaPath: '$(Pipeline.Workspace)/build/appstore/output/*.ipa'
              releaseTrack: 'TestFlight'
              shouldSkipWaitingForProcessing: true
              shouldSkipSubmission: true
              appSpecificId: $(AppleAppID)
```
