### ISSUE TITLE
what does shouldSkipSubmission really do?

### ISSUE THREAD

**Issue by Crare** [microsoft/app-store-vsts-extension#391]
readme says: 
_Skip Submission (Checkbox) - Upload a beta app without distributing to testers._

it seems that it doesn't skip automatic distribution groups in Testflight for the app.
External testers group doesn't even have setting to make it automatic so I don't really see what else it would be skipping than the groups that are automatically distributed to but that is not what it does or at least it's not working for that. So what does it really do?

I have these settings in pipeline for this task for example:

```
- task: AppStoreRelease@1
  displayName: (${{ parameters.environment }}) distribute ios-app to Testflight
  inputs:
    authType: "ServiceEndpoint"
    serviceEndpoint: ${{ variables.APPLE_ServiceEndpointId }}
    releaseTrack: "TestFlight"
    appIdentifier: "${{ variables.APP_BUNDLE_ID }}"
    appType: "iOS"
    ipaPath: releases_drop/drop/ios/build/${{ parameters.environment }}/*.ipa
    shouldSkipWaitingForProcessing: true
    shouldSkipSubmission: true
    appSpecificId: ${{ variables.APPLE_appId }}
    teamId: $(variables.APPLE_teamId)
```
